eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/apps


microservice:
  movies-service:
    endpoints:
      endpoint-stock: http://localhost:8091/api/v1/movies/
      endpoint-stock-by-labelle: http://localhost:8091/api/v1/movies/get-movie-by-movie-title/{movieTitle}
        
