spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/medabbassi/webservice-config.git
          username: medabbassi
          password:
server:
  port: 9898

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
